In [ ]:
#!pip3 install numpy

## <font color='orange'>What is NumPy</font>

<ul><li>Provides multi-dimensional array object.</li>
    <li>Provides tools for working with arrays.</li>
</ul>

## <font color='green'>Why use NumPy (vs List)</font>

<ol>
    <li>Size</li>
    <li>Performance</li>
    <li>Operations</li>
</ol>

### Performance comparision

In [1]:
import numpy as np
import time

In [4]:
def list_version(size_of_array):
    t = time.time()
    a = range(size_of_array)
    b = range(size_of_array)
    c = [a[i] + b[i] for i in range(len(a)) ]
    return time.time() - t

In [5]:
def numpy_version(size_of_array):
    t = time.time()
    a = np.arange(size_of_array)
    b = np.arange(size_of_array)
    c = a + b
    return time.time() - t

In [6]:
size_of_array = 1000
print('Time taken using list (sec):', list_version(size_of_array))
print('Time taken using Numpy (sec):', numpy_version(size_of_array))

Time taken using list (sec): 0.0
Time taken using Numpy (sec): 0.0


### Operations

In [7]:
x = list(range(10))
y = list(range(10))
x + y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
x = np.arange(10)
y = np.arange(10)
x + y

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# <font color='blue'>What we will learn:</font>

<ol>
    <li>Creating numpy arrays</li>
    <li>Array with random numbers</li>
    <li>Array methods and attributes</li>
    <li>Indexing and Slicing</li>
    <li>NumPy Operations</li>
    <li>Storing and Reading NumPy arrays</li>
</ol>

## <font color='green'>1. Creating numpy arrays</font>

### From List

In [19]:
a = [2,3,5,7,3,10]

In [20]:
np.array(a)

array([ 2,  3,  5,  7,  3, 10])

In [21]:
b = [[1,2,5],[4,3,10]]

In [22]:
np.array(b)

array([[ 1,  2,  5],
       [ 4,  3, 10]])

### Using arange

In [ ]:
a = np.arange(0, #starting number
              10) #Stop number - excluded
a

In [ ]:
np.arange(0, #start
          10, #stop
          2) #step

### Array using 0s and 1s

In [91]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [92]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones((3,6))

### linspace

In [5]:
np.linspace(1, #start number
            10, #Last number - not excluded
            5)  #How many numbers

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### eye matrix

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## <font color='green'>2. Array using random numbers</font>

#### <font color='blue'>rand</font> - Using uniform distribution

In [7]:
np.random.rand(4)

array([0.2830588 , 0.63447323, 0.47119371, 0.38653127])

In [8]:
np.random.rand(2,3)

array([[0.5235758 , 0.00759366, 0.47808079],
       [0.09981585, 0.21071823, 0.95976233]])

#### <font color='blue'>randn</font> - Using normal distribution

In [9]:
np.random.randn(4,3)

array([[ 1.17396736,  0.05980988,  0.1550346 ],
       [-0.92144451, -0.75106122,  2.11721257],
       [-0.87749964,  0.40243051, -0.18413244],
       [-0.06818022, -1.3215229 , -0.25309641]])

#### <font color='blue'>randint</font> - generating random integer(s)

In [10]:
np.random.randint(5,20)

13

In [11]:
np.random.randint(5,20,3)

array([ 8, 12, 10])

#### <font color='blue'>Seed</font> - Bringing sanity to randomness

In [12]:
np.random.randint(1,100,3)


array([38, 70, 95])

In [13]:
np.random.seed(100)
np.random.randint(1,100,3)

array([ 9, 25, 68])

## <font color='orange'>3. Array methods and attributes</font>

### Shape

In [14]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
b = np.random.randn(4,3)
b

array([[ 0.74805333, -2.49385259, -0.18571172],
       [-0.19009702, -0.53934796, -0.5833315 ],
       [ 1.073201  , -0.13702713,  0.17086301],
       [-0.59970748,  2.65975058,  0.99683627]])

In [20]:
print(a.shape)
print(b.shape)

(20,)
(4, 3)


### Reshape

In [21]:
c = a.reshape(4,5)
print(c.shape)
c

(4, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### max, min, argmax and argmin

In [34]:
a = np.random.rand(3,4)
a

array([[0.21706577, 0.52695039, 0.42710838, 0.98263043],
       [0.14045149, 0.7484116 , 0.78884039, 0.73039662],
       [0.84561834, 0.55619038, 0.05686271, 0.88672457]])

In [36]:
a.max()

0.9826304270905724

In [37]:
a.argmax()

3

In [25]:
print(b.min())
print(b.argmin())

0.005817191449534076
0


### Array data type

In [26]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
a.dtype

dtype('int32')

In [28]:
b

array([[0.00581719, 0.30742321, 0.95018431, 0.12665424],
       [0.07898787, 0.31135313, 0.63238359, 0.69935892],
       [0.64196495, 0.92002378, 0.29887635, 0.56874553]])

In [29]:
b.dtype

dtype('float64')

In [30]:
a.astype('float32')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.], dtype=float32)

## <font color='green'>4. Indexing and Slicing</font>

#### Using brackets

In [ ]:
a = np.arange(11,25)
a

In [ ]:
a[5]

In [ ]:
a[2:6]

In [ ]:
#Specific elements
a[[0,3,6]]

In [ ]:
#Updating specific elements
a[3:5] = 100
a

### Two dimensional array indexing and slicing

In [38]:
b = np.array([[10,32,6,7,8], [90, 45, 32 , 89, 50], 
              [33, 66, 99, 22, 55], [23, 56, 98, 45, 65]])
b

array([[10, 32,  6,  7,  8],
       [90, 45, 32, 89, 50],
       [33, 66, 99, 22, 55],
       [23, 56, 98, 45, 65]])

In [39]:
#indexing row
b[1]

array([90, 45, 32, 89, 50])

In [40]:
#Specific element
b[2][3]

22

In [93]:
#Same as above
b[2,3]

IndexError: too many indices for array

In [45]:
#Specific rows and columns
b[:,2].T

array([ 6, 32, 99, 98])

### Custom indexing

In [ ]:
b = np.array([[10,32,6,7,8], [90, 45, 32 , 89, 50], 
              [33, 66, 99, 22, 55], [23, 56, 98, 45, 65]])
b

In [ ]:
b[:,(1,3)]

### Subset

In [46]:
b


array([[10, 32,  6,  7,  8],
       [90, 45, 32, 89, 50],
       [33, 66, 99, 22, 55],
       [23, 56, 98, 45, 65]])

In [47]:
c = b[:2,1:]
c

array([[32,  6,  7,  8],
       [45, 32, 89, 50]])

In [48]:
c[:] = 200
c

array([[200, 200, 200, 200],
       [200, 200, 200, 200]])

In [ ]:
b

### Copy

In [62]:
b = np.array([[10,32,6,7,8], [90, 45, 32 , 89, 50], 
              [33, 66, 99, 22, 55], [23, 56, 98, 45, 65]])

y=b[(3,2,1),:]
y

array([23, 56, 98, 45, 65])

In [50]:
d = b.copy()
d

array([[10, 32,  6,  7,  8],
       [90, 45, 32, 89, 50],
       [33, 66, 99, 22, 55],
       [23, 56, 98, 45, 65]])

In [51]:
d[:] = 500
d

array([[500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500]])

In [52]:
b

array([[10, 32,  6,  7,  8],
       [90, 45, 32, 89, 50],
       [33, 66, 99, 22, 55],
       [23, 56, 98, 45, 65]])

### Selection

In [68]:
a = np.arange(30, 45)
a

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [69]:
b = a < 35
b

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False])

In [70]:
a[b]

array([30, 31, 32, 33, 34])

In [77]:
c = [a > 35] and [a < 20]
a[c]

array([], dtype=int32)

## <font color='orange'>5. NumPy Operations</font>

### Arithmatic operations

In [94]:
a = np.arange(10, 25)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [95]:
a + a

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [96]:
a - 1

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [ ]:
a * a

In [ ]:
a / a

In [ ]:
a ** 2

In [ ]:
100/ a

### Universal operations

In [64]:
a = np.arange(10, 50, 3)
a

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [65]:
np.sqrt(a)  #Square root of each element


array([3.16227766, 3.60555128, 4.        , 4.35889894, 4.69041576,
       5.        , 5.29150262, 5.56776436, 5.83095189, 6.08276253,
       6.32455532, 6.55743852, 6.78232998, 7.        ])

In [66]:
np.exp(a)  #Exponent of each element

array([2.20264658e+04, 4.42413392e+05, 8.88611052e+06, 1.78482301e+08,
       3.58491285e+09, 7.20048993e+10, 1.44625706e+12, 2.90488497e+13,
       5.83461743e+14, 1.17191424e+16, 2.35385267e+17, 4.72783947e+18,
       9.49611942e+19, 1.90734657e+21])

In [ ]:
np.square(a) #Square of each element

In [ ]:
np.sin(a)  #Trignometric sine

In [ ]:
np.log(a)  #log

### Universal operations. . .

In [82]:
a = np.random.rand(4,5)
a

array([[0.1139206 , 0.36841365, 0.36074842, 0.88001849, 0.27454204],
       [0.22458118, 0.81397318, 0.05820075, 0.73015342, 0.03267909],
       [0.59998723, 0.03054111, 0.85960489, 0.43977952, 0.56044466],
       [0.81740526, 0.0890063 , 0.70148773, 0.38557212, 0.01742254]])

In [83]:
np.round(a,2)  #rounding to 2 decimal places

array([[0.11, 0.37, 0.36, 0.88, 0.27],
       [0.22, 0.81, 0.06, 0.73, 0.03],
       [0.6 , 0.03, 0.86, 0.44, 0.56],
       [0.82, 0.09, 0.7 , 0.39, 0.02]])

In [84]:
np.round(a)  #rounding to 0 decimal places

array([[0., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0.]])

In [85]:
np.std(a)  #Calculate standard variance

0.300871988389591

In [86]:
np.var(a) #Calculate variance

0.0905239533975062

In [87]:
np.mean(a) #Mean / average

0.417924109165026

### Unique operation

In [79]:
a = np.array(['Orange', 'Mango', 'Apple', 'Apple', 'Banana', 'Mango', 'banana'])
a

array(['Orange', 'Mango', 'Apple', 'Apple', 'Banana', 'Mango', 'banana'],
      dtype='<U6')

In [80]:
np.unique(a)

array(['Apple', 'Banana', 'Mango', 'Orange', 'banana'], dtype='<U6')

## <font color='brown'>6. Storing and reading NumPy</font>

### Saving and Restoring

In [ ]:
array_1 = np.arange(10, 20)
array_2 = np.arange(30,50, 3)

In [ ]:
np.save('ar_1',  #File name , will be saved with .npy extension
        array_1 ) #Array to be saved

In [ ]:
np.load('ar_1.npy')

### Saving two arrays into single file

In [ ]:
np.savez('ar_multi',  #file name, extension will be .npz
         a=array_1, 
         b=array_2)

In [ ]:
saved_array = np.load('ar_multi.npz')
saved_array['b']

### Saving as txt file

In [ ]:
np.savetxt('ar_1.txt', array_1, delimiter=',')

In [ ]:
np.loadtxt('ar_1.txt', delimiter=',')